### ISSUE TITLE
Update repo structure to match pixi-ui

### ISSUE THREAD

**Issue by CyberDex** [pixijs/layout#1]
# Info

pixi-ui was updated to use pixi-extension-scripts and follow a more consistent repo structure that matches other pixi projects. This project needs the same work done

# Tasks

- [ ] Deploy gh-page through github-actions
- [x] Use pixi-extension-scripts for building, linting etc
- [x] Add husky for pre-commit lint checking
- [x] Add workflow files for release notes and PR testing
